
[general]
	#The material blacklist of this module.
	materialBlacklist = []

[recipes]
	#The materials that should not have material melting recipes added.
	materialToLiquidMaterialBlacklist = []
	#The materials that should not have block melting recipes added.
	blockToLiquidMaterialBlacklist = []
	#The materials that should not have nugget melting recipes added.
	nuggetToLiquidMaterialBlacklist = []
	#The materials that should not have dust melting recipes added.
	dustToLiquidMaterialBlacklist = []
	#The materials that should not have plate melting recipes added.
	plateToLiquidMaterialBlacklist = []
	#The materials that should not have gear melting recipes added.
	gearToLiquidMaterialBlacklist = []
	#The materials that should not have material casting recipes added.
	toMaterialMaterialBlacklist = []
	#The materials that should not have block casting recipes added.
	toBlockMaterialBlacklist = []
	#The materials that should not have atomizer to dust recipes added.
	toDustMaterialBlacklist = []
	#The materials that should not have plate casting recipes added.
	toPlateMaterialBlacklist = []
	#The materials that should not have gear casting recipes added.
	toGearMaterialBlacklist = []
	#Should the module only add recipes for materials with JAOPCA molten fluids.
	jaopcaOnly = false
	#The materials that should not have material casting recipes added.
	moltenToMaterialMaterialBlacklist = []
	#The materials that should not have molten block casting recipes added.
	moltenToBlockMaterialBlacklist = []
	#The materials that should not have atomizer molten to dust recipes added.
	moltenToDustMaterialBlacklist = []
	#The materials that should not have molten plate casting recipes added.
	moltenToPlateMaterialBlacklist = []
	#The materials that should not have molten gear casting recipes added.
	moltenToGearMaterialBlacklist = []

