
#Configurations for material Bismuth.
[general]
	#The alternative names of this material.
	alternativeNames = []
	#The byproducts of this material.
	extras = []
	#Is the storage block of this material small (2x2).
	isSmallStorageBlock = false
	#The module blacklist of this material.
	moduleBlacklist = []
	#Should items of this material have the enchanted glow.
	hasEffect = false
	#The model type of the material.
	modelType = "metallic"
	#The color of this material.
	color = 10856368

[foundry]
	#The temperature of this Foundry liquid metal.
	temperature = 1300

[molten]
	#The temperature of this molten fluid.
	temperature = 1300

[enderio]
	#The default byproduct material to output in Ender IO's sagmill.
	byproduct = "minecraft:cobblestone"

[tconstruct]
	#The base smeltery temperature of this material.
	temperature = 600

[hbm]
	#The default byproduct material to output in HBMNTM's centrifuge.
	byproduct = "minecraft:gravel"

[mariculture]
	#The base smeltery temperature of this material.
	temperature = 1100
	#The default byproduct material to output in Mariculture's crucible if no extra material is defined.
	byproduct = "minecraft:stone"

[avaritia]
	#The base amount of blocks required to create one singularity.
	inputAmount = 300
	#Should the singularity be added to the Infinity Catalyst recipe.
	addToCatalyst = true

