
[general]
	#The material blacklist of this module.
	materialBlacklist = []

[recipes]
	#The materials that should not have duster material to dust recipes added.
	materialToDustMaterialBlacklist = []
	#The materials that should not have duster block to dust recipes added.
	blockToDustMaterialBlacklist = []

